language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
script: grunt crossbrowser
env:
  global:
  - secure: MD956nghcfbAiBhfglwPmF0tfbhXvV5u/hRE9lynvuTV7QR0cVfDDKFrgNWono1CYbkMMJWV62Hc4i+7LfdznK2+zmKDDNl6q84odFNzkYlCFwVaPuu7vvE6cQOJ5CtJqR//sohEW0Tf88/yDkBUL+kgazhGXES1DePFgg2hb9I=
  - secure: GE8l9KX8zn5bNFMBI3jFhjUSmsilNBb5Q9tS1Ce78zoCQYfTo+AeAOA+K/z2LP4OXWfAWDks4X4l74icucSd5G+T8/Gxpw1r85WlGAsUyQQU/teeWO4Cb5omoJHgiB8FI0l3zKspQOS6PmXOQqTgyPzhlVe3+b1OeHQDLLJglFA=
